export default function Head() {
  return (
    <>
      <title>ConsigAki - Home</title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="stylesheet" />
      <link
        rel="preload"
        href="/_next/static/css/app/(app)/layout.css?v=1687200200064"
        as="style"
      />
    </>
  )
}
